import { describe, expect, test } from 'bun:test';
import encode_qr, { utils } from '../src/index';
import { encode_email, encode_url, encode_wifi } from '../src/links';

type QrFixtureOutput = 'ascii' | 'svg' | 'gif';

interface QrFixtureCase {
  readonly id: string;
  readonly input: string;
  readonly output: QrFixtureOutput;
  readonly expected: { readonly length: number, readonly sha256: string };
}

interface QrFixtureFile {
  readonly cases: readonly QrFixtureCase[];
}

interface LinkFixtureFile {
  readonly url: { readonly input: string, readonly expected: string };
  readonly email: {
    readonly input: { readonly address: string, readonly options: { readonly subject: string, readonly body: string } },
    readonly expected: string
  };
  readonly wifi: {
    readonly input: { readonly ssid: string, readonly password: string, readonly security: 'WPA' | 'WEP' | 'nopass' },
    readonly expected: string
  };
}

const qrFixtures = await Bun.file(new URL('./fixtures/qr-fixtures.json', import.meta.url)).json() as QrFixtureFile;
const linkFixtures = await Bun.file(new URL('./fixtures/link-fixtures.json', import.meta.url)).json() as LinkFixtureFile;

/**
 * IMPORTANT — what these fixtures do and do not prove.
 *
 * The `length` and `sha256` values in `tests/fixtures/qr-fixtures.json` were generated by
 * THIS encoder. They are therefore CHANGE DETECTORS, not correctness oracles: they prove
 * the output is byte-for-byte stable across refactors, but they cannot prove the output is
 * a spec-conformant QR symbol. If the encoder were wrong, these fixtures would faithfully
 * lock in the wrong bytes.
 *
 * Consequence: a legitimate fix can turn these red. Mask selection depends on penalty
 * scoring, so correcting a penalty rule per ISO/IEC 18004 §6.8.2.2 legitimately changes the
 * chosen mask for some payloads and thus the hash — that is a fixture update, not a bug.
 * Before re-baselining any value here, confirm the new output is spec-correct rather than
 * simply different.
 *
 * The actual correctness oracle lives in `tests/roundtrip.test.ts`, which validates rendered
 * symbols against ISO/IEC 18004 (format-information BCH(15,5), version BCH(18,6), function
 * pattern geometry, and published byte-capacity limits) using arithmetic that shares no code
 * with `src/`. It covers these same fixture payloads specifically so that a mask change is
 * verified against the spec, not just re-hashed.
 *
 * These tests are kept because byte-stability regression detection is genuinely valuable —
 * just do not mistake a green run here for proof of conformance.
 *
 * On authoritative golden vectors: ISO/IEC 18004 is a paywalled standard and its worked
 * examples could not be sourced reliably in this environment. Rather than invent vectors and
 * present them as authoritative, the spec-derived structural checks in roundtrip.test.ts
 * (whose BCH generator polynomials, format XOR mask, and capacity figures ARE independently
 * specified values) serve as the independent check.
 */
describe('fixtures: qr encoding', () => {
  for (const fixture of qrFixtures.cases) {
    test(`matches fixture: ${fixture.id}`, async () => {
      const output = encodeFixtureOutput(fixture.input, fixture.output);
      const length = typeof output === 'string' ? output.length : output.length;
      const bytes = toBytes(output);
      const hash = await sha256(bytes);

      expect(length).toBe(fixture.expected.length);
      expect(hash).toBe(fixture.expected.sha256);
    });
  }
});

describe('fixtures: link encoding', () => {
  test('matches URL fixture', () => {
    expect(encode_url(linkFixtures.url.input)).toBe(linkFixtures.url.expected);
  });

  test('matches email fixture', () => {
    expect(encode_email(linkFixtures.email.input.address, linkFixtures.email.input.options)).toBe(linkFixtures.email.expected);
  });

  test('matches WiFi fixture', () => {
    expect(encode_wifi(linkFixtures.wifi.input)).toBe(linkFixtures.wifi.expected);
  });
});

/**
 * Regression tests for the input-validation defects catalogued in `_dev/reviews/002`.
 *
 * Each block reproduces the exact call that previously either returned a silently wrong
 * result or leaked a raw engine error, and asserts the actionable `Error` now thrown.
 * The "valid input unchanged" tests in each block guard against over-eager validation:
 * these fixes must not narrow the accepted surface of the public API.
 */
describe('validation: text_encoder return value', () => {
  // Previously an encoder returning a string flowed into `encode_payload`, where iterating it
  // and shifting NaN produced a valid, scannable symbol encoding NUL bytes.
  test('rejects a non-Uint8Array return', () => {
    expect(() => encode_qr('secret-payload', 'raw', { encoding: 'byte', text_encoder: (() => 'nope') as never })).toThrow(
      /text_encoder must return a Uint8Array, got string/
    );
  });

  test('rejects an array return', () => {
    expect(() => encode_qr('x', 'raw', { encoding: 'byte', text_encoder: (() => [1, 2, 3]) as never })).toThrow(
      /text_encoder must return a Uint8Array, got object/
    );
  });

  test('rejects a null return', () => {
    expect(() => encode_qr('x', 'raw', { encoding: 'byte', text_encoder: (() => null) as never })).toThrow(
      /text_encoder must return a Uint8Array, got null/
    );
  });

  test('is validated on the version-selection path too', () => {
    // No explicit `version`, so `select_version` calls the encoder before `encode` does.
    expect(() => encode_qr('secret-payload', 'raw', { encoding: 'byte', text_encoder: (() => 'nope') as never })).toThrow(/text_encoder/);
  });

  test('a conforming encoder still matches the default output', () => {
    const custom = encode_qr('secret-payload', 'ascii', { encoding: 'byte', text_encoder: (t) => new TextEncoder().encode(t) });
    expect(custom).toBe(encode_qr('secret-payload', 'ascii', { encoding: 'byte' }));
  });
});

describe('validation: info.format_bits', () => {
  // An unknown ecc key yielded `undefined << 3` === 0 — exactly `medium`'s code — so a typo
  // silently produced a symbol readable only as medium ecc.
  test('rejects an unknown error correction level instead of aliasing to medium', () => {
    expect(() => utils.info.format_bits('bogus' as never, 0)).toThrow(/Invalid error correction mode=bogus/);
    expect(utils.info.format_bits('medium', 0)).toBe(21522);
  });

  test('rejects an out-of-range mask', () => {
    // 99 previously produced 129182 — a 17-bit value in a 15-bit spec field.
    expect(() => utils.info.format_bits('low', 99 as never)).toThrow(/Invalid mask=99/);
    expect(() => utils.info.format_bits('low', -1 as never)).toThrow(/Invalid mask=-1/);
    expect(() => utils.info.format_bits('low', 1.5 as never)).toThrow(/Invalid mask=1.5/);
  });

  test('every valid ecc/mask pair still fits the 15-bit format field', () => {
    for (const ecc of ['low', 'medium', 'quartile', 'high'] as const) {
      for (let mask = 0;mask < 8;mask++) {
        const bits = utils.info.format_bits(ecc, mask as never);
        expect(bits).toBeGreaterThanOrEqual(0);
        expect(bits).toBeLessThan(1 << 15);
      }
    }
  });
});

describe('validation: info.capacity', () => {
  test('rejects an unknown error correction level with an actionable message', () => {
    // Previously a raw `TypeError: undefined is not an object` from indexing the ecc tables.
    expect(() => utils.info.capacity(5 as never, 'nope' as never)).toThrow(/Invalid error correction mode=nope/);
  });

  test('rejects an out-of-range version', () => {
    expect(() => utils.info.capacity(0 as never, 'medium')).toThrow(/Invalid version=0/);
    expect(() => utils.info.capacity(41 as never, 'medium')).toThrow(/Invalid version=41/);
  });
});

describe('validation: utils.draw_template', () => {
  // `info.size.encode` is pure arithmetic, so an unvalidated version produced a structurally
  // malformed bitmap rather than throwing: ver 0 -> 17x17, ver 41 -> 181x181, ver 2.5 -> 27x27.
  test('rejects out-of-range and non-integer versions', () => {
    for (const ver of [0, -1, 41, 2.5, Number.NaN]) {
      expect(() => utils.draw_template(ver as never, 'medium', 0)).toThrow(/Invalid version=/);
    }
  });

  test('rejects an unknown ecc level and an out-of-range mask', () => {
    expect(() => utils.draw_template(utils.validate_version(1), 'bogus' as never, 0)).toThrow(/Invalid error correction mode=bogus/);
    expect(() => utils.draw_template(utils.validate_version(1), 'medium', 8 as never)).toThrow(/Invalid mask=8/);
  });

  test('every valid version still yields the spec-sized template', () => {
    for (let ver = 1;ver <= 40;ver++) {
      const tpl = utils.draw_template(utils.validate_version(ver), 'medium', 0);
      expect(tpl.data.length).toBe(21 + 4 * (ver - 1));
    }
  });
});

describe('validation: encode_qr arguments', () => {
  test('rejects a non-string text instead of leaking a raw TypeError', () => {
    for (const text of [12345, null, {}, undefined, [], true]) {
      expect(() => encode_qr(text as never, 'raw')).toThrow(/Invalid text type=.*Expected string/);
    }
  });

  test('rejects a null or non-object opts', () => {
    expect(() => encode_qr('hi', 'ascii', null as never)).toThrow(/Invalid opts type=null/);
    expect(() => encode_qr('hi', 'ascii', 7 as never)).toThrow(/Invalid opts type=number/);
  });

  test('an empty string is still a valid payload', () => {
    expect(typeof encode_qr('', 'ascii')).toBe('string');
  });
});

describe('validation: border bounds', () => {
  test('rejects a negative border instead of leaking a RangeError from fill_arr', () => {
    expect(() => encode_qr('hi', 'ascii', { border: -1 })).toThrow(/invalid border: -1\. Expected number \[0\.\.1024\]/);
  });

  test('rejects an absurdly large border instead of allocating a giant matrix', () => {
    // `border: 20000` used to allocate a 40021x40021 matrix; `border: 100000` never returned.
    for (const border of [1025, 20000, 100000]) {
      expect(() => encode_qr('hi', 'ascii', { border })).toThrow(/invalid border/);
    }
  });

  test('still rejects non-integer borders', () => {
    expect(() => encode_qr('hi', 'ascii', { border: 1.5 })).toThrow(/invalid border/);
    expect(() => encode_qr('hi', 'ascii', { border: Number.NaN })).toThrow(/invalid border/);
  });

  test('accepts the full valid range including the bounds', () => {
    for (const border of [0, 1, 2, 4, 1024]) {
      expect(encode_qr('hi', 'raw', { border }).length).toBe(21 + 2 * border);
    }
  });
});

function toBytes(value: string | Uint8Array): Uint8Array {
  return typeof value === 'string' ? new TextEncoder().encode(value) : value;
}

function encodeFixtureOutput(input: string, output: QrFixtureOutput): string | Uint8Array {
  if (output === 'ascii') {
    return encode_qr(input, 'ascii');
  }
  if (output === 'svg') {
    return encode_qr(input, 'svg');
  }
  return encode_qr(input, 'gif');
}

async function sha256(bytes: Uint8Array): Promise<string> {
  const data = new Uint8Array(bytes.length);
  data.set(bytes);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join('');
}
