import { describe, expect, test } from 'bun:test';
import encode_qr from '../src/index';
import { encode_email, encode_url, encode_wifi } from '../src/links';

type QrFixtureOutput = 'ascii' | 'svg' | 'gif';

interface QrFixtureCase {
  readonly id: string;
  readonly input: string;
  readonly output: QrFixtureOutput;
  readonly expected: { readonly length: number, readonly sha256: string };
}

interface QrFixtureFile {
  readonly cases: readonly QrFixtureCase[];
}

interface LinkFixtureFile {
  readonly url: { readonly input: string, readonly expected: string };
  readonly email: {
    readonly input: { readonly address: string, readonly options: { readonly subject: string, readonly body: string } },
    readonly expected: string
  };
  readonly wifi: {
    readonly input: { readonly ssid: string, readonly password: string, readonly security: 'WPA' | 'WEP' | 'nopass' },
    readonly expected: string
  };
}

const qrFixtures = await Bun.file(new URL('./fixtures/qr-fixtures.json', import.meta.url)).json() as QrFixtureFile;
const linkFixtures = await Bun.file(new URL('./fixtures/link-fixtures.json', import.meta.url)).json() as LinkFixtureFile;

/**
 * IMPORTANT — what these fixtures do and do not prove.
 *
 * The `length` and `sha256` values in `tests/fixtures/qr-fixtures.json` were generated by
 * THIS encoder. They are therefore CHANGE DETECTORS, not correctness oracles: they prove
 * the output is byte-for-byte stable across refactors, but they cannot prove the output is
 * a spec-conformant QR symbol. If the encoder were wrong, these fixtures would faithfully
 * lock in the wrong bytes.
 *
 * Consequence: a legitimate fix can turn these red. Mask selection depends on penalty
 * scoring, so correcting a penalty rule per ISO/IEC 18004 §6.8.2.2 legitimately changes the
 * chosen mask for some payloads and thus the hash — that is a fixture update, not a bug.
 * Before re-baselining any value here, confirm the new output is spec-correct rather than
 * simply different.
 *
 * The actual correctness oracle lives in `tests/roundtrip.test.ts`, which validates rendered
 * symbols against ISO/IEC 18004 (format-information BCH(15,5), version BCH(18,6), function
 * pattern geometry, and published byte-capacity limits) using arithmetic that shares no code
 * with `src/`. It covers these same fixture payloads specifically so that a mask change is
 * verified against the spec, not just re-hashed.
 *
 * These tests are kept because byte-stability regression detection is genuinely valuable —
 * just do not mistake a green run here for proof of conformance.
 *
 * On authoritative golden vectors: ISO/IEC 18004 is a paywalled standard and its worked
 * examples could not be sourced reliably in this environment. Rather than invent vectors and
 * present them as authoritative, the spec-derived structural checks in roundtrip.test.ts
 * (whose BCH generator polynomials, format XOR mask, and capacity figures ARE independently
 * specified values) serve as the independent check.
 */
describe('fixtures: qr encoding', () => {
  for (const fixture of qrFixtures.cases) {
    test(`matches fixture: ${fixture.id}`, async () => {
      const output = encodeFixtureOutput(fixture.input, fixture.output);
      const length = typeof output === 'string' ? output.length : output.length;
      const bytes = toBytes(output);
      const hash = await sha256(bytes);

      expect(length).toBe(fixture.expected.length);
      expect(hash).toBe(fixture.expected.sha256);
    });
  }
});

describe('fixtures: link encoding', () => {
  test('matches URL fixture', () => {
    expect(encode_url(linkFixtures.url.input)).toBe(linkFixtures.url.expected);
  });

  test('matches email fixture', () => {
    expect(encode_email(linkFixtures.email.input.address, linkFixtures.email.input.options)).toBe(linkFixtures.email.expected);
  });

  test('matches WiFi fixture', () => {
    expect(encode_wifi(linkFixtures.wifi.input)).toBe(linkFixtures.wifi.expected);
  });
});

function toBytes(value: string | Uint8Array): Uint8Array {
  return typeof value === 'string' ? new TextEncoder().encode(value) : value;
}

function encodeFixtureOutput(input: string, output: QrFixtureOutput): string | Uint8Array {
  if (output === 'ascii') {
    return encode_qr(input, 'ascii');
  }
  if (output === 'svg') {
    return encode_qr(input, 'svg');
  }
  return encode_qr(input, 'gif');
}

async function sha256(bytes: Uint8Array): Promise<string> {
  const data = new Uint8Array(bytes.length);
  data.set(bytes);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, '0')).join('');
}
